name: Deploy Nginx Configs

on:
  push:
    branches: [main]
    paths:
      - "conf/**"

permissions:
  contents: read

jobs:
  nginx-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > ec2_key.pem
          chmod 400 ec2_key.pem

      - name: Copy Nginx Configs to EC2
        run: |
          # Copy default.conf
          scp -o StrictHostKeyChecking=no -i ec2_key.pem conf/default.conf ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/etc/nginx/conf.d/default.conf

          # Copy nginx.conf
          scp -o StrictHostKeyChecking=no -i ec2_key.pem conf/nginx.conf ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/etc/nginx/nginx.conf

      - name: Test and Reload Nginx
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo nginx -t
            sudo systemctl reload nginx
          EOF
